apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-assign1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-assign1
  template: 
    metadata: # Dictionary
      name: mlops-assign1-pod
      labels: # Dictionary 
        app: mlops-assign1         
    spec:
      containers: # List
        - name: mlops-assign1-container
          image: bijua/mlops-assign1:latest
          ports:
            - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  type: ClusterIP 
  selector: 
    app: mlops-assign1
  ports: 
    - name: http
      port: 5001
      targetPort: 5001
